public enum STATES {
  INIT_PLAYERS, INTRODUCE_MAFIAS, INTRODUCE_DR_TO_MAYOR, BEGIN_DAY, WIN_LOST_CHECK, MAFIA_WINNER, CITIZEN_WINNER,
  ENABLE_CHAT, END_OF_DAY_VOTING, DISABLE_CHAT, ONLY_VOTING_CHAT, MAYOR_DECISIONING, BEGIN_NIGHT, MAFIA_GATHERING,
  PSYCHOLOGIST, PROFESSIONAL, DETECTIVE, DIEHARD, DR_LACTER, GOD_FATHER, DR_CITY

}